services:
  - type: web
    name: my-web-service
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node index.js'
    envVars:
      - key: NODE_VERSION
        value: 20.15.1
